apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE
  namespace: dev
  labels:
    app: SERVICE
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: SERVICE
  template:
    metadata:
      labels:
        app: SERVICE
    spec:
      containers:
        - name: SERVICE
          image: registry-np.geminisolutions.com/SERVICE
          ports:
            - name: SERVICE
              containerPort: 5000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
